on:
  workflow_dispatch:
  schedule:
    - cron: '20 */24 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        SKIP_UPDATED: '1'
